---

guardianManagementApi:
  home: "/guardian_service_dir"
  requestsCaBundle: "/etc/ssl/certs/ca-certificates.crt"
  sslCertFile: "/etc/ssl/certs/ca-certificates.crt"
  guardianManagementCorsAllowedOrigins: "*"
  guardianManagementAdapterSettingsPort: "env"
  guardianManagementAdapterAppPersistencePort: "sql"
  guardianManagementAdapterConditionPersistencePort: "sql"
  guardianManagementAdapterContextPersistencePort: "sql"
  guardianManagementAdapterNamespacePersistencePort: "sql"
  guardianManagementAdapterPermissionPersistencePort: "sql"
  guardianManagementAdapterRolePersistencePort: "sql"
  guardianManagementAdapterCapabilityPersistencePort: "sql"
  guardianManagementAdapterAuthenticationPort: "fast_api_oauth"
  guardianManagementAdapterAuthorizationApiUrl: "http://guardian-management-api/guardian/authorization"
  guardianManagementAdapterResourceAuthorizationPort: "guardian"
  isUniventionAppCenter: 0
  sqlPersistenceAdapterDialect: "postgresql"
  sqlPersistenceAdapterDbName: "/guardian_service_dir/database/management.db"
  oauthAdapterWellKnownUrl: "http://keycloak/realms/souvap/.well-known/openid-configuration"
  oauthAdapterM2mSecret: "stub_secret"
  guardianManagementLoggingLevel: "DEBUG"
  guardianManagementLoggingStructured: "0"
  guardianManagementLoggingFormat: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS ZZ}</green> | <level>{level}</level> | <level>{message}</level> | {extra}"
  guardianManagementBaseUrl: "http://guardian-management"

postgresql:
  # -- Set to `true` if you want PostgreSQL to be installed as well.
  bundled: true
  # -- Connection parameters. These are required if you use an external database.
  connection:
    host:
    port:
  auth:
    username: "selfservice"
    database: "selfservice"
    password: "easyPassword"
    postgresPassword: "postgres"

...
