#!/bin/sh

## joinscript api: bindpwdfile

#
#  Join script that runs on the docker host.
#

VERSION=3
APP_ID="guardian-management-api"
APP_DIR="/var/lib/univention-appcenter/apps/$APP_ID"

. /usr/share/univention-join/joinscripthelper.lib || exit 1
. /usr/share/univention-appcenter/joinscripthelper.sh || exit 1
eval "$(ucr shell)" || exit 1

joinscript_init

if [ $JS_LAST_EXECUTED_VERSION -lt 1 ]; then
  ucs_registerLDAPExtension "$@" \
    --packagename "$APP_ID" \
    --packageversion "$VERSION" \
    --schema "/var/lib/univention-appcenter/apps/$APP_ID/conf/guardian.schema" \
    --udm_syntax "/var/lib/univention-appcenter/apps/$APP_ID/conf/guardian_syntax.py" \
    --udm_syntax_messagecatalog "/var/lib/univention-appcenter/apps/$APP_ID/locale/DE/LC_MESSAGES/de.mo" \
    --ucsversionstart 5.0-0 || die

  udm settings/extended_attribute create "$@" --ignore_exists \
    --position "cn=custom attributes,cn=univention,$ldap_base" \
    --set name="guardianRole" \
    --set tabName="Guardian" \
    --set shortDescription="Roles used by Guardian for access permissions" \
    --set translationShortDescription='"de_DE" "Die Rollen, welche vom Guardian zur Authorisation genutzt werden."' \
    --set longDescription="Lowercase ASCII alphanumeric string with underscores or dashes, in the format 'app:namespace:role' or 'app:namespace:role&app:namespace:context'" \
    --set translationLongDescription="\"de_DE\" \"ASCII alphanumerischer Text in Kleinschrift mit Unter- und Bindestrichen im Format 'app:namespace:role' oder 'app:namespace:role&app:namespace:context'\"" \
    --set mayChange=1 \
    --set multivalue=1 \
    --append module="users/user" \
    --append module="groups/group" \
    --set objectClass=univentionGuardianObject \
    --set syntax=GuardianRole \
    --set ldapMapping=univentionGuardianRole || die
fi

# Creating and configuring the Keycloak clients is safe to rerun multiple times
API_FQDN="$hostname.$domainname"
univention-keycloak "$@" oidc/rp create \
    --name guardian \
    --app-url "https://$API_FQDN" \
    --redirect-uri "https://$API_FQDN/guardian/*" \
    --add-audience-mapper guardian || die
univention-keycloak "$@" oidc/rp create \
    --name guardian-cli \
    --app-url "https://$API_FQDN" \
    --redirect-uri "https://$API_FQDN/guardian/*" \
    --add-audience-mapper guardian-cli || die
$APP_DIR/scripts/configure-keycloak "$@"

if [ $JS_LAST_EXECUTED_VERSION -eq 1 ]; then
    # In version 2, we renamed the UCR variable for storing the Keycloak secret
    # that Guardian uses to talk with the Authorization API
    old_keycloak_secret=$(ucr get guardian-management-api/oauth/keycloak-cli-client-secret)
    univention-app configure guardian-management-api --set "guardian-management-api/oauth/keycloak-client-secret=$old_keycloak_secret"
fi

if [ $JS_LAST_EXECUTED_VERSION -le 2 ]; then
    # removed settings containing secrets
    univention-app configure guardian-management-api --unset \
        "guardian-management-api/oauth/keycloak-client-secret" \
        "guardian-management-api/oauth/keycloak-cli-client-secret"
    if ! test -f /var/lib/univention-appcenter/apps/guardian-management-api/conf/m2m.secret; then
        ucr get guardian-management-api/oauth/keycloak-client-secret > /var/lib/univention-appcenter/apps/guardian-management-api/conf/m2m.secret
        chmod 600 /var/lib/univention-appcenter/apps/guardian-management-api/conf/m2m.secret
        univention-app configure $APP_ID
        univention-app restart $APP_ID
    fi
    ucr unset \
        "guardian-management-api/oauth/keycloak-client-secret" \
        "guardian-management-api/oauth/keycloak-cli-client-secret"
fi

joinscript_save_current_version

exit $?
