#!/bin/sh

## joinscript api: bindpwdfile

#
#  Join script that runs on the docker host.
#

VERSION=1

APP_ID="guardian-management-api"

. /usr/share/univention-join/joinscripthelper.lib

joinscript_init

# nothing to do, this unjoin script exists solely to execute:

joinscript_remove_script_from_status_file "$APP_ID"

exit 0
