#!/bin/sh

## joinscript api: bindpwdfile

#
#  Join script that runs on the docker host.
#

VERSION=2

APP_ID="guardian-management-api"

. /usr/share/univention-join/joinscripthelper.lib || exit 1
eval "$(ucr shell)" || exit 1

joinscript_init

udm computers/"$server_role" modify "$@" --dn "$ldap_hostdn" --remove service="guardian-management-api" || die

joinscript_remove_script_from_status_file "$APP_ID"

exit 0
