---

apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  serviceName: {{ include "common.names.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}'
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: '{{ .Chart.Name }}-api'
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ if .Values.image.guardianAuthorizationApi.registry }}{{ .Values.image.guardianAuthorizationApi.registry }}/{{ end }}{{ .Values.image.guardianAuthorizationApi.repository }}{{ if .Values.image.guardianAuthorizationApi.sha256 }}@sha256:{{ .Values.image.guardianAuthorizationApi.sha256 }}{{ else }}:{{ .Values.image.guardianAuthorizationApi.tag }}{{ end }}'
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          envFrom:
            - configMapRef:
                name: '{{ include "common.names.fullname" . }}'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: '{{ .Chart.Name }}-opa'
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ if .Values.image.openPolicyAgent.registry }}{{ .Values.image.openPolicyAgent.registry }}/{{ end }}{{ .Values.image.openPolicyAgent.repository }}{{ if .Values.image.openPolicyAgent.sha256 }}@sha256:{{ .Values.image.openPolicyAgent.sha256 }}{{ else }}:{{ .Values.image.openPolicyAgent.tag }}{{ end }}'
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          envFrom:
            - configMapRef:
                name: '{{ include "common.names.fullname" . }}'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
...
