# Copyright (C) 2023-2026 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

include:
  - local: /.gitlab-ci/ai-review.yml
    rules:
      - if: $RUN_RENOVATE != "yes"
  - project: univention/infrastructure/docker-services
    file:
      - renovatebot/renovate.gitlab-ci.yml
    rules:
      - if: $RUN_RENOVATE == "yes"
  - project: "univention/dev/nubus-for-k8s/common-ci"
    ref: "v1.64.0"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
  - component: "$CI_SERVER_FQDN/univention/dev/tooling/ci-components/debian-aptly@2.5.2"
    inputs:
      pkg-dir: univention-guardian

variables:
  # Bump this when starting a new UCS release branch.
  UCS_VERSION: "5.2-5"
  RUN_RENOVATE:
    value: "no"
    options:
      - "yes"
      - "no"
    description: "Set to yes if you want to run renovate"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "webide"
    - if: $CI_COMMIT_TAG
    - if: $RUN_RENOVATE == "yes"

lint-pre-commit:
  extends: .lint-pre-commit
  variables:
    RUNNER_REGISTRY_IMAGE: "gitregistry.knut.univention.de/univention/dev/tooling/pre-commit/univention-pre-commit"
    RUNNER_IMAGE_TAG: "0.6.2"
