# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 Univention GmbH

---
version: 0

global:
  ignore:
    - ".kubeVersion"
    - ".global.kubeVersion"
    - ".extensions.*"
    - ".systemExtensions.*"
    - ".global.extensions.*"
    - ".global.systemExtensions.*"
