# Copyright (C) 2023 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
        exclude: management-ui/
    -   id: check-xml
    -   id: check-yaml
    -   id: check-toml
    -   id: trailing-whitespace
    -   id: pretty-format-json
        args: [--autofix]
        exclude: management-ui/
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        exclude: "udm_client.py"
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        exclude: "authorization-api/tests/|port-loader/tests/|management-api/tests|udm_client.py|guardian-lib/tests"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        exclude: "docs/|authorization-api/tests/|port-loader/tests/|management-api/tests|guardian-lib/tests"
        args: []
        additional_dependencies: [fastapi==0.95.2, loguru==0.7.0, requests==2.31.0, types-requests==2.31.0, alembic==1.11.3, types-aiofiles]
- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.9
  hooks:
    - id: pymarkdown
      exclude: ".gitlab/issue_templates/"
      args:
        - --disable-rules
        - MD013,MD024,MD034,MD041
        - scan
        # Rules pymarkdown: https://github.com/jackdewinter/pymarkdown/blob/main/docs/rules.md
        # Rules markdownlint: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
        # MD013: Allow arbitrary line length
        # MD024: Allow duplicate headings
        # MD034: Allow bare URLs
        # MD041: First line in file should be a top level heading

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.270'
  hooks:
    - id: ruff
      args: [--fix]
      exclude: "udm_client.py"
- repo: https://github.com/python-poetry/poetry
  rev: '1.5.1'
  hooks:
    - id: poetry-check
      args: ["-C", "authorization-api"]
    - id: poetry-check
      args: [ "-C", "port-loader" ]
    - id: poetry-check
      args: [ "-C", "management-api" ]
    - id: poetry-check
      args: [ "-C", "guardian-lib" ]
    - id: poetry-lock
      args: ["-C", "authorization-api", "--check"]
    - id: poetry-lock
      args: [ "-C", "port-loader", "--check" ]
    - id: poetry-lock
      args: [ "-C", "management-api", "--check" ]
    - id: poetry-lock
      args: [ "-C", "guardian-lib", "--check" ]

- repo: https://github.com/anderseknert/pre-commit-opa
  rev: v1.5.1
  hooks:
  - id: opa-fmt
  - id: opa-check
    args: ["management-api/rego_policy_bundle_template"]
  - id: opa-check
    args: [ "management-api/alembic/1.0.0_builtin_conditions", "--ignore=\"*.json\"" ]
  - id: opa-test
    args: ["management-api/rego_policy_bundle_template"]
  - id: opa-test
    args: [ "management-api/alembic/1.0.0_builtin_conditions", "--ignore=\"*.json\"" ]

- repo: https://github.com/StyraInc/regal
  rev: v0.8.0
  hooks:
    - id: regal-lint-use-path
