# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
        exclude: frontend/conffiles/usr/share/ucs-school-ui-users-frontend/app/config.json
    -   id: check-xml
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: pretty-format-json
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        exclude: "docs/"
        args: []
        additional_dependencies: [fastapi==0.95.2]
- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.9
  hooks:
    - id: pymarkdown
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.270'
  hooks:
    - id: ruff
