#!/usr/bin/bash
source .env
if [ "postgres" = "$1" ]
then
	COMPOSEFILES="-f dev-compose.yaml -f dev-compose-postgres.yaml"
else
  COMPOSEFILES="-f dev-compose.yaml"
fi

mkdir -p management_service_dir/
USER_ID=$(id --user) GITLAB_IP=$(getent -i ahostsv4 git.knut.univention.de | head -n 1 | cut -d ' ' -f 1) exec docker compose $COMPOSEFILES up --build
