# Copyright (C) 2023 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

services:
  proxy:
    image: traefik:v2.10
    command: --providers.docker --entryPoints.web.address=:80
    networks:
      - proxy-net
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  opa:
    container_name: opa-guardian-dev
    image: guardian-opa:dev
    build: opa/
    networks:
      - proxy-net
  authorization-api:
    container_name: authz-guardian-dev
    image: guardian-authorization-api:dev
    build:
      context: authorization-api/
      target: dev
      extra_hosts:
        - git.knut.univention.de:${GITLAB_IP}
    depends_on:
      - opa
    networks:
      - proxy-net
    volumes:
      - ./authorization-api:/app
    environment:
      - GUARDIAN__AUTHZ__LOGGING__LEVEL
      - GUARDIAN__AUTHZ__LOGGING__STRUCTURED
      - GUARDIAN__AUTHZ__ADAPTER__SETTINGS_PORT
      - GUARDIAN__AUTHZ__ADAPTER__PERSISTENCE_PORT
      - GUARDIAN__AUTHZ__ADAPTER__POLICY_PORT
      - GUARDIAN__AUTHZ__API_PREFIX
      - UDM_DATA_ADAPTER__USERNAME
      - UDM_DATA_ADAPTER__PASSWORD
      - UDM_DATA_ADAPTER__URL
      - OPA_ADAPTER__URL
    labels:
      traefik.http.routers.authz.entrypoints: web
      traefik.http.routers.authz.rule: PathPrefix(`/guardian/authorization`)
      traefik.http.routers.authz.service: authz
      traefik.http.services.authz.loadbalancer.server.port: 8000
  management-api:
    container_name: management-guardian-dev
    image: guardian-management-api:dev
    build:
      context: management-api/
      target: dev
      extra_hosts:
        - git.knut.univention.de:${GITLAB_IP}
    depends_on:
      - opa
    networks:
      - proxy-net
    volumes:
      - ./management-api:/app
    environment:
      - GUARDIAN__MANAGEMENT__LOGGING__LEVEL
      - GUARDIAN__MANAGEMENT__LOGGING__STRUCTURED
      - GUARDIAN__MANAGEMENT__ADAPTER__SETTINGS_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__APP_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__BASE_URL
    labels:
      traefik.http.routers.management.entrypoints: web
      traefik.http.routers.management.rule: PathPrefix(`/guardian/management`)
      traefik.http.routers.management.service: management
      traefik.http.services.management.loadbalancer.server.port: 8000
networks:
  proxy-net:
    name: proxy-net
