# Copyright (C) 2023 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

services:
  proxy:
    image: traefik:v2.10
    hostname: traefik
    command:
     - --providers.docker
     - --entryPoints.web.address=:80
    networks:
      - proxy-net
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  opa:
    container_name: opa-guardian-dev
    image: guardian-opa:dev
    build: opa/
    networks:
      - proxy-net
    environment:
      - OPA_DATA_BUNDLE
      - OPA_POLICY_BUNDLE
      - OPA_GUARDIAN_MANAGEMENT_URL
      - OPA_POLLING_MIN_DELAY
      - OPA_POLLING_MAX_DELAY
    labels:
      traefik.http.routers.opa.entrypoints: web
      traefik.http.routers.opa.rule: PathPrefix(`/guardian/opa`)
      traefik.http.routers.opa.middlewares: opa-stripprefix
      traefik.http.middlewares.opa-stripprefix.stripprefix.prefixes: /guardian/opa
      traefik.http.routers.opa.service: opa
      traefik.http.services.opa.loadbalancer.server.port: 8181
  authorization-api:
    container_name: authz-guardian-dev
    image: guardian-authorization-api:dev
    build:
      context: ./
      dockerfile: authorization-api/Dockerfile
      target: dev
      extra_hosts:
        - git.knut.univention.de:${GITLAB_IP}
        - ucs-sso-ng.school.test:${UCS_HOST_IP}
    extra_hosts:
      - ucs-sso-ng.school.test:${UCS_HOST_IP}
    depends_on:
      opa:
        condition: service_started
      proxy:
        condition: service_started
      keycloak:
        condition: service_healthy
    networks:
      - proxy-net
    volumes:
      - ./authorization-api:/app/authorization-api
      - type: bind
        source: ./management_service_dir
        target: /guardian_service_dir
    environment:
      - GUARDIAN__AUTHZ__CORS__ALLOWED_ORIGINS
      - GUARDIAN__AUTHZ__LOGGING__LEVEL
      - GUARDIAN__AUTHZ__LOGGING__STRUCTURED
      - GUARDIAN__AUTHZ__ADAPTER__SETTINGS_PORT
      - GUARDIAN__AUTHZ__ADAPTER__PERSISTENCE_PORT
      - GUARDIAN__AUTHZ__ADAPTER__POLICY_PORT
      - GUARDIAN__AUTHZ__ADAPTER__AUTHENTICATION_PORT
      - GUARDIAN__AUTHZ__API_PREFIX
      - UDM_DATA_ADAPTER__USERNAME
      - UDM_DATA_ADAPTER__PASSWORD
      - UDM_DATA_ADAPTER__URL
      - OPA_ADAPTER__URL
      - OAUTH_ADAPTER__WELL_KNOWN_URL
      - REQUESTS_CA_BUNDLE
      - SSL_CERT_FILE
    labels:
      traefik.http.routers.authz.entrypoints: web
      traefik.http.routers.authz.rule: PathPrefix(`/guardian/authorization`)
      traefik.http.routers.authz.service: authz
      traefik.http.services.authz.loadbalancer.server.port: 8000
  db_provisioning:
    container_name: db_provisioning
    image: guardian-management-api:dev
    entrypoint: alembic
    command: upgrade head
    user: ${USER_ID:-1000}
    working_dir: /app/management-api
    build:
      context: ./
      dockerfile: management-api/Dockerfile
      target: dev
      extra_hosts:
        - git.knut.univention.de:${GITLAB_IP}
    depends_on:
      keycloak:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./management-api:/app/management-api
      - type: bind
        source: ./management_service_dir
        target: /guardian_service_dir
    labels:
      traefik.enable: "false"
    environment:
      - UCS_HOST_IP
      - GUARDIAN__MANAGEMENT__LOGGING__LEVEL
      - GUARDIAN__MANAGEMENT__LOGGING__STRUCTURED
      - GUARDIAN__MANAGEMENT__ADAPTER__SETTINGS_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__APP_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CONDITION_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CONTEXT_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__NAMESPACE_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__PERMISSION_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__ROLE_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CAPABILITY_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__AUTHENTICATION_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__RESOURCE_AUTHORIZATION_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__AUTHORIZATION_API_URL
      - GUARDIAN__MANAGEMENT__BASE_URL
      - SQL_PERSISTENCE_ADAPTER__DIALECT
      - SQL_PERSISTENCE_ADAPTER__DB_NAME
      - OAUTH_ADAPTER__WELL_KNOWN_URL
      - REQUESTS_CA_BUNDLE
      - SSL_CERT_FILE
    networks:
      - proxy-net
  management-api:
    container_name: management-guardian-dev
    image: guardian-management-api:dev
    user: ${USER_ID:-1000}
    build:
      context: ./
      dockerfile: management-api/Dockerfile
      target: dev
      extra_hosts:
        - git.knut.univention.de:${GITLAB_IP}
    extra_hosts:
      - ucs-sso-ng.school.test:${UCS_HOST_IP}
    depends_on:
      db_provisioning:
        condition: service_started
      proxy:
        condition: service_started
      keycloak:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - proxy-net
    volumes:
      - ./management-api:/app/management-api
      - type: bind
        source: ./management_service_dir
        target: /guardian_service_dir
    environment:
      - UCS_HOST_IP
      - GUARDIAN__MANAGEMENT__CORS__ALLOWED_ORIGINS
      - GUARDIAN__MANAGEMENT__LOGGING__LEVEL
      - GUARDIAN__MANAGEMENT__LOGGING__STRUCTURED
      - GUARDIAN__MANAGEMENT__ADAPTER__SETTINGS_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__APP_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CONDITION_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CONTEXT_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__NAMESPACE_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__PERMISSION_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__ROLE_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CAPABILITY_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__AUTHENTICATION_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__RESOURCE_AUTHORIZATION_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__AUTHORIZATION_API_URL
      - GUARDIAN__MANAGEMENT__BASE_URL
      - SQL_PERSISTENCE_ADAPTER__DIALECT
      - SQL_PERSISTENCE_ADAPTER__DB_NAME
      - OAUTH_ADAPTER__WELL_KNOWN_URL
      - OAUTH_ADAPTER__M2M_SECRET
      - REQUESTS_CA_BUNDLE
      - SSL_CERT_FILE
    labels:
      traefik.http.routers.management.entrypoints: web
      traefik.http.routers.management.rule: PathPrefix(`/guardian/management`)
      traefik.http.routers.management.service: management
      traefik.http.services.management.loadbalancer.server.port: 8000
  keycloak:
    container_name: keycloak-guardian-dev
    image: keycloak-guardian:dev
    build:
      context: ./
      dockerfile: keycloak/Dockerfile
    hostname: keycloak
    command: start --optimized
    healthcheck:
      test: "/opt/keycloak/bin/kcadm.sh get realms/GuardianDev --server http://localhost:8080/guardian/keycloak --realm master --user admin --password admin"
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 40s
      start_interval: 2s
    depends_on:
      - proxy
      - keycloak-provisioning
    networks:
      - proxy-net
    labels:
      traefik.http.routers.keycloak.entrypoints: web
      traefik.http.routers.keycloak.rule: PathPrefix(`/guardian/keycloak`)
      traefik.http.routers.keycloak.service: keycloak
      traefik.http.services.keycloak.loadbalancer.server.port: 8080
      traefik.http.middlewares.customheaders.headers.customrequestheaders.X-Forwarded-Proto: http
      traefik.http.routers.keycloak.middlewares: customheaders

  keycloak-provisioning:
    container_name: keycloak-provisioning-dev
    image: keycloak-guardian-provisioning:dev
    build:
      context: ./
      dockerfile: keycloak/provisioning/Dockerfile
    networks:
      - proxy-net
    labels:
      traefik.enable: "false"
  db:
    image: python:3.11.5-alpine
    restart: unless-stopped
    stop_signal: SIGINT
    container_name: dummy-db-service
    command: python3 -m http.server
    networks:
      - proxy-net
    healthcheck:
      test: ["CMD", "sleep", "0.1"]

  management-ui:
    container_name: management-ui
    image: management-ui:dev
    build:
      context: ./
      dockerfile: management-ui/docker/Dockerfile
      extra_hosts:
        - git.knut.univention.de:${GITLAB_IP}
    networks:
      - proxy-net
    environment:
      - VITE__MANAGEMENT_UI__ADAPTER__AUTHENTICATION_PORT=keycloak
      - VITE__MANAGEMENT_UI__ADAPTER__DATA_PORT=api
      - VITE__KEYCLOAK_AUTHENTICATION_ADAPTER__SSO_URI
      - VITE__KEYCLOAK_AUTHENTICATION_ADAPTER__REALM
      - VITE__KEYCLOAK_AUTHENTICATION_ADAPTER__CLIENT_ID
      - VITE__API_DATA_ADAPTER__URI

    labels:
      traefik.http.routers.management-ui.entrypoints: web
      traefik.http.routers.management-ui.rule: PathPrefix(`/univention/guardian/management-ui`)
      traefik.http.routers.management-ui.service: management-ui
      traefik.http.services.management-ui.loadbalancer.server.port: 80


networks:
  proxy-net:
    name: proxy-net
