# Copyright (C) 2023 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

services:
  proxy:
    image: traefik:v2.10
    command: --providers.docker --entryPoints.web.address=:80
    networks:
      - proxy-net
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  opa:
    container_name: opa-guardian-dev
    image: guardian-opa:dev
    build: opa/
    networks:
      - proxy-net
    environment:
      - OPA_DATA_BUNDLE
      - OPA_POLICY_BUNDLE
      - OPA_GUARDIAN_MANAGEMENT_URL
      - OPA_POLLING_MIN_DELAY
      - OPA_POLLING_MAX_DELAY
    labels:
      traefik.http.routers.opa.entrypoints: web
      traefik.http.routers.opa.rule: PathPrefix(`/guardian/opa`)
      traefik.http.routers.opa.middlewares: opa-stripprefix
      traefik.http.middlewares.opa-stripprefix.stripprefix.prefixes: /guardian/opa
      traefik.http.routers.opa.service: opa
      traefik.http.services.opa.loadbalancer.server.port: 8181
  authorization-api:
    container_name: authz-guardian-dev
    image: guardian-authorization-api:dev
    build:
      context: ./
      dockerfile: authorization-api/Dockerfile
      target: dev
      extra_hosts:
        - git.knut.univention.de:${GITLAB_IP}
    depends_on:
      - opa
      - proxy
    networks:
      - proxy-net
    volumes:
      - ./authorization-api:/app/authorization-api
    environment:
      - GUARDIAN__AUTHZ__LOGGING__LEVEL
      - GUARDIAN__AUTHZ__LOGGING__STRUCTURED
      - GUARDIAN__AUTHZ__ADAPTER__SETTINGS_PORT
      - GUARDIAN__AUTHZ__ADAPTER__PERSISTENCE_PORT
      - GUARDIAN__AUTHZ__ADAPTER__POLICY_PORT
      - GUARDIAN__AUTHZ__ADAPTER__AUTHENTICATION_PORT
      - GUARDIAN__AUTHZ__API_PREFIX
      - UDM_DATA_ADAPTER__USERNAME
      - UDM_DATA_ADAPTER__PASSWORD
      - UDM_DATA_ADAPTER__URL
      - OPA_ADAPTER__URL
      - OAUTH_ADAPTER__WELL_KNOWN_URL
      - OAUTH_ADAPTER__WELL_KNOWN_URL_SECURE
    labels:
      traefik.http.routers.authz.entrypoints: web
      traefik.http.routers.authz.rule: PathPrefix(`/guardian/authorization`)
      traefik.http.routers.authz.service: authz
      traefik.http.services.authz.loadbalancer.server.port: 8000
  db_provisioning:
    container_name: db_provisioning
    image: guardian-management-api:dev
    entrypoint: alembic
    command: upgrade head
    user: ${USER_ID:-1000}
    working_dir: /app/management-api
    build:
      context: ./
      dockerfile: management-api/Dockerfile
      target: dev
      extra_hosts:
        - git.knut.univention.de:${GITLAB_IP}
    volumes:
      - ./management-api:/app/management-api
      - type: bind
        source: ./management_service_dir
        target: /guardian_service_dir
    environment:
      - GUARDIAN__MANAGEMENT__LOGGING__LEVEL
      - GUARDIAN__MANAGEMENT__LOGGING__STRUCTURED
      - GUARDIAN__MANAGEMENT__ADAPTER__SETTINGS_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__APP_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CONDITION_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CONTEXT_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__NAMESPACE_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__PERMISSION_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__ROLE_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__BASE_URL
      - SQL_PERSISTENCE_ADAPTER__DIALECT
      - SQL_PERSISTENCE_ADAPTER__DB_NAME
  management-api:
    container_name: management-guardian-dev
    image: guardian-management-api:dev
    user: ${USER_ID:-1000}
    build:
      context: ./
      dockerfile: management-api/Dockerfile
      target: dev
      extra_hosts:
        - git.knut.univention.de:${GITLAB_IP}
    depends_on:
      - proxy
      - db_provisioning
    networks:
      - proxy-net
    volumes:
      - ./management-api:/app/management-api
      - type: bind
        source: ./management_service_dir
        target: /guardian_service_dir
    environment:
      - GUARDIAN__MANAGEMENT__LOGGING__LEVEL
      - GUARDIAN__MANAGEMENT__LOGGING__STRUCTURED
      - GUARDIAN__MANAGEMENT__ADAPTER__SETTINGS_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__APP_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CONDITION_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__CONTEXT_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__NAMESPACE_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__PERMISSION_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__ADAPTER__ROLE_PERSISTENCE_PORT
      - GUARDIAN__MANAGEMENT__BASE_URL
      - SQL_PERSISTENCE_ADAPTER__DIALECT
      - SQL_PERSISTENCE_ADAPTER__DB_NAME
    labels:
      traefik.http.routers.management.entrypoints: web
      traefik.http.routers.management.rule: PathPrefix(`/guardian/management`)
      traefik.http.routers.management.service: management
      traefik.http.services.management.loadbalancer.server.port: 8000
networks:
  proxy-net:
    name: proxy-net
