sonar.projectKey=univention_dev_projects_authorization-engine_guardian_7eb9204b-4aeb-44d0-9c27-1a9b135a76e1
sonar.qualitygate.wait=true
#sonar.sources=authorization-api/guardian_authorization_api,authorization-client/guardian_authorization_client,guardian-lib/guardian_lib,management-api/guardian_management_api,management-ui/src
#sonar.tests=authorization-api/tests,guardian-lib/guardian_pytest,guardian-lib/tests,management-api/tests,management-ui/src/tests
sonar.python.coverage.reportPaths=*/coverage.xml
sonar.python.version=3.11
sonar.links.homepage=https://git.knut.univention.de/univention/dev/projects/authorization-engine/guardian
sonar.links.issue=https://git.knut.univention.de/univention/dev/projects/authorization-engine/guardian/-/issues
sonar.links.scm=https://git.knut.univention.de/univention/dev/projects/authorization-engine/guardian
