# Copyright (C) 2023-2026 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

include:
  - project: univention/infrastructure/docker-services
    file:
      - kaniko.yml
      - pre-commit.yml
  - project: "univention/dev/nubus-for-k8s/common-ci"
    ref: "v1.52.1"
    file:
      - "jobs/generate-filesystem-sbom.yaml"
      - "templates/sonarqube.yaml"
  - project: 'univention/dev/docs/sphinx-docker'
    file: 'pipeline/sphinx.yml'
  - component: $CI_SERVER_FQDN/univention/dev/internal/ucsschool-ci-utils/app-release@2
    inputs:
      app_id: "guardian-authorization-api"
      job_prefix: "authz-"
      mail_sender: "nubus-core@univention.de"
      author_alias: "Nubus Core Team"
      changelog_link: "https://docs.software-univention.de/guardian-manual/latest/changelogs.html#authorization-api"
      mail_recipient: "app-announcement@univention.de"
      chat_destination: "#ucsschool"
      ucs_base_version: "5.0"
      additional_update_appcenter_needs:
        - job: build_docker_image_authz
          optional: true
        - job: build_docker_image_opa
          optional: true
        - authz_keycloak_script
      appcenter_file_dir: "appcenter-authz/"
      release_tag_prefix: "authorization-api_"
  - component: $CI_SERVER_FQDN/univention/dev/internal/ucsschool-ci-utils/app-release@2
    inputs:
      app_id: "guardian-management-api"
      job_prefix: "management-"
      mail_sender: "nubus-core@univention.de"
      author_alias: "Nubus Core Team"
      changelog_link: "https://docs.software-univention.de/guardian-manual/latest/changelogs.html#management-api"
      mail_recipient: "app-announcement@univention.de"
      chat_destination: "#ucsschool"
      ucs_base_version: "5.0"
      additional_update_appcenter_needs:
        - management_keycloak_script
        - job: build_docker_image_management
          optional: true
      appcenter_file_dir: "appcenter-management/"
      release_tag_prefix: "management-api_"
  - component: $CI_SERVER_FQDN/univention/dev/internal/ucsschool-ci-utils/app-release@2
    inputs:
      app_id: "guardian-management-ui"
      job_prefix: "management-ui-"
      mail_sender: "nubus-core@univention.de"
      author_alias: "Nubus Core Team"
      changelog_link: "https://docs.software-univention.de/guardian-manual/latest/changelogs.html#management-ui"
      mail_recipient: "app-announcement@univention.de"
      chat_destination: "#ucsschool"
      ucs_base_version: "5.0"
      additional_update_appcenter_needs:
        - management-ui_keycloak_script
        - job: build_docker_image_management_ui
          optional: true
      appcenter_file_dir: "appcenter-management-ui/"
      release_tag_prefix: "management-ui_"

  - component: $CI_SERVER_FQDN/univention/dev/nubus-for-k8s/common-ci/pip-package-and-publish-with-uv@jlohmer-uv-publish
    inputs:
      package_root: "authorization-client"


variables:
  APPCENTER_CONTROL_IMAGE: "docker-registry.knut.univention.de/knut/univention-appcenter-control"
  POETRY_VERSION: "2.2.1"
  UCS_VERSION: "505"
  UCS_RELEASE: "5.0"
  DEB_IMAGE: docker-registry.knut.univention.de/phahn/ucs-debbase:$UCS_VERSION
  UCSLINT_IMAGE: gitregistry.knut.univention.de/univention/ucs
  SCOPE: "guardian"
  DOCS_DIR: "docs/guardian-manual"
  DOC_TARGET_VERSION: "3.0"
  DOC_TARGET_NAME: "guardian-manual"
  DOC_TARGET_PATH: "$DOC_TARGET_NAME/$DOC_TARGET_VERSION"

#TODO: Stages should be merged and reduced by smart needs
#and handling of the python packages in docker builds
stages:
  - prepare
  - test
  - build_python
  - build_docker
  - package
  - publish
  - build
  - merge
  - release
  - production
  - cleanup

build_testrunner:
  stage: prepare
  needs: []
  extends: .kaniko
  variables:
    IMAGE_TAG_ENV_NAME: "IMAGE_TAG_TESTRUNNER"
    DOCKERFILE_PATH: "$CI_PROJECT_DIR/docker/testrunner/Dockerfile"
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/guardian-testrunner
    KANIKO_ARGS: --cache=true --cache-repo=$CI_REGISTRY_IMAGE/cache

# No jobs for OPA code were created, since the form and structure of the OPA code is not final yet. TODO
test:
  stage: test
  needs:
    - job: build_testrunner
      artifacts: true
  image: $IMAGE_TAG_TESTRUNNER
  variables:
    UV_PROJECT_ENVIRONMENT: "/opt/venv"
  script:
    - exit_code=0
    - >-
      uv run pytest guardian-lib/tests/ -lvv
      --cov=guardian_lib
      --cov-fail-under=100
      --cov-report=term-missing
      --cov-report=xml:guardian-lib/coverage.xml
      --junit-xml=guardian-lib/pytest-junit.xml
      || exit_code=1
    - >-
      uv run pytest authorization-api/tests/ -lvv
      --cov=guardian_authorization_api
      --cov-fail-under=73
      --cov-report=term-missing
      --cov-report=xml:authorization-api/coverage.xml
      --junit-xml=authorization-api/pytest-junit.xml
      || exit_code=1
    - >-
      uv run pytest management-api/tests/ -lvv
      --cov=guardian_management_api
      --cov-fail-under=99
      --cov-report=term-missing
      --cov-report=xml:management-api/coverage.xml
      --junit-xml=management-api/pytest-junit.xml
      || exit_code=1
    - exit $exit_code
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - "*/coverage.xml"
    reports:
      coverage_report:
        coverage_format: cobertura
        path: "*/coverage.xml"
      junit:
        - "guardian-lib/pytest-junit.xml"
        - "authorization-api/pytest-junit.xml"
        - "management-api/pytest-junit.xml"
    expire_in: "1 day"
    when: "always"

generate-filesystem-sbom:
  stage: "build_docker"
  variables:
    FOLDER: "management-ui"


build_docker_image_opa:
  stage: build_docker
  rules:
    - if: "$CI_COMMIT_TAG"
      variables:
        REGISTRY: "artifacts.software-univention.de"
        REGISTRY_IMAGE: "$REGISTRY/ucsschool/guardian-opa"
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  extends: .kaniko
  variables:
    IMAGE_TAG_ENV_NAME: "IMAGE_TAG_OPA"
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR/opa"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/guardian-opa
    KANIKO_ARGS: --build-arg commit="$CI_COMMIT_SHA" --build-arg date="$CI_JOB_STARTED_AT" --cache=true --cache-repo=$CI_REGISTRY_IMAGE/cache

build_docker_image_management_ui:
  needs: ["generate-filesystem-sbom"]
  stage: build_docker
  rules:
    - if: "$CI_COMMIT_TAG"
      variables:
        REGISTRY: "artifacts.software-univention.de"
        REGISTRY_IMAGE: "$REGISTRY/ucsschool/guardian-management-ui"
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  extends: .kaniko
  variables:
    DOCKERFILE_PATH: "$CI_PROJECT_DIR/management-ui/docker/Dockerfile"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/guardian-management-ui
    KANIKO_ARGS: --build-arg commit="$CI_COMMIT_SHA" --build-arg date="$CI_JOB_STARTED_AT" --cache=true --cache-repo=$CI_REGISTRY_IMAGE/cache

build_docker_image_authz:
  stage: build_docker
  rules:
    - if: "$CI_COMMIT_TAG"
      variables:
        REGISTRY: "artifacts.software-univention.de"
        REGISTRY_IMAGE: "$REGISTRY/ucsschool/guardian-authorization-api"
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  extends: .kaniko
  variables:
    IMAGE_TAG_ENV_NAME: "IMAGE_TAG_AUTHZ"
    DOCKERFILE_PATH: "$CI_PROJECT_DIR/authorization-api/Dockerfile"
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/guardian-authorization-api
    KANIKO_ARGS: --build-arg commit="$CI_COMMIT_SHA" --build-arg date="$CI_JOB_STARTED_AT" --skip-unused-stages --cache=true --cache-repo=$CI_REGISTRY_IMAGE/cache

build_docker_image_management:
  stage: build_docker
  rules:
    - if: "$CI_COMMIT_TAG"
      variables:
        REGISTRY: "artifacts.software-univention.de"
        REGISTRY_IMAGE: "$REGISTRY/ucsschool/guardian-management-api"
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  extends: .kaniko
  variables:
    DOCKERFILE_PATH: "$CI_PROJECT_DIR/management-api/Dockerfile"
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/guardian-management-api
    KANIKO_ARGS: --build-arg commit="$CI_COMMIT_SHA" --build-arg date="$CI_JOB_STARTED_AT" --skip-unused-stages --cache=true --cache-repo=$CI_REGISTRY_IMAGE/cache


.generate_keycloak_script:
  stage: build_docker
  image: gitregistry.knut.univention.de/univention/dev/internal/ucsschool-ci-utils/app-release:latest
  variables:
    APP_NAME: "guardian-authorization-api"
    CONFIGURE_KEYCLOAK_TEMPLATE: "appcenter-authz/includes/configure-keycloak.tmpl"
    KEYCLOAK_TEMP_FILE: "appcenter-authz/includes/keycloak_script.include"
  script:
    - ./appcenter-common/keycloak/generate-configure-keycloak.sh "$APP_NAME" "$CONFIGURE_KEYCLOAK_TEMPLATE" "$KEYCLOAK_TEMP_FILE"
  artifacts:
    paths:
      - ${KEYCLOAK_TEMP_FILE}

authz_keycloak_script:
  extends: .generate_keycloak_script

management_keycloak_script:
  extends: .generate_keycloak_script
  variables:
    APP_NAME: "guardian-management-api"
    CONFIGURE_KEYCLOAK_TEMPLATE: "appcenter-management/includes/configure-keycloak.tmpl"
    KEYCLOAK_TEMP_FILE: "appcenter-management/includes/keycloak_script.include"

management-ui_keycloak_script:
  extends: .generate_keycloak_script
  variables:
    APP_NAME: "guardian-management-ui"
    CONFIGURE_KEYCLOAK_TEMPLATE: "appcenter-management-ui/includes/configure-keycloak.tmpl"
    KEYCLOAK_TEMP_FILE: "appcenter-management-ui/includes/keycloak_script.include"

docs-linkcheck:
  extends: .sphinx-linkcheck-template
  rules:
    - changes:
      - $DOCS_DIR/**/*

docs-spelling:
  extends: .sphinx-spelling-template
  rules:
    - changes:
      - $DOCS_DIR/**/*

docs-html:
  extends: .sphinx-html-template
  rules:
    - changes:
      - $DOCS_DIR/**/*

docs-pdf:
  extends: .sphinx-pdf-template
  rules:
    - changes:
      - $DOCS_DIR/**/*

docs-merge-to-one-artifact:
  extends: .sphinx-merge-template
  needs:
    - job: docs-html
    - job: docs-pdf
    - job: docs-spelling
      artifacts: false
    - job: docs-linkcheck
      artifacts: false
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
      - $DOCS_DIR/**/*
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - $DOCS_DIR/**/*
      when: manual

docs-review:
  extends: .sphinx-review-template
  needs:
    - job: docs-merge-to-one-artifact
  rules:
    - changes:
      - $DOCS_DIR/**/*

# The template has inherit:variables:false to prevent the passing of pipeline
# variables to downstream, and therefore $DOCS_DIR is not available here.
docs-create-production-merge-request:
  extends: .sphinx-docs-merge-request-template
  needs:
    - job: docs-merge-to-one-artifact
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - docs/guardian-manual/**/*

pip-package-and-publish-with-uv:
  variables:
    RELEASE_VERSION: "0.1.0-dev"

sonarqube:
  extends: .sonarqube
  stage: test
  needs: [test]
