---

apiVersion: v2
name: "open-policy-agent"
description: "OPA is a full-featured policy engine that offloads policy decisions from your service."

type: "application"

version: "0.1.0"

appVersion: "0.53.0"

dependencies:
  - name: "common"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/common-helm/helm"
    version: "^0.6.0"

...
