---

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
replicaCount: 1
securityContext: {}
tolerations: []

guardianManagementUi:
  viteManagementUiAdapterAuthenticationPort: "keycloak"
  viteManagementUiAdapterDataPort: "api"
  # -- URL for the Guardian Management API.
  viteApiDataAdapterUri: "http://localhost:8000/guardian/management"
  # -- Base URI of the Keycloak server for authentication.
  viteKeycloakAuthenticationAdapterSsoUri: "http://localhost:8097"
  # -- Keycloak authentication realm.
  viteKeycloakAuthenticationAdapterRealm: "ucs"
  # -- Keycloak client ID.
  viteKeycloakAuthenticationAdapterClientId: "guardian-ui"

ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: true
  ingressClassName: "nginx"
  host: null
  paths:
    - pathType: Prefix
      path: /univention/guardian/management-ui
      backend:
        service:
          name: guardian-management-ui
          port:
            number: 80
  tls:
    enabled: true
    secretName: ""

istio:
  # -- Set this to `true` in order to enable the installation on Istio related objects.
  enabled: false
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  virtualService:
    enabled: true
    annotations: {}
    # -- The paths configuration.
    # The default only grabs what is known to be handled by the UMC server.
    paths:
      - match: "prefix"
        path: "/univention/guardian/management-ui/"
        rewrite: "/univention/guardian/management-ui/"
  gateway:
    enabled: false
    annotations:
    selectorIstio: "ingressgateway"
    externalGatewayName: "swp-istio-gateway"
    tls:
      enabled: true
      httpsRedirect: true
      secretName: ""

image:
  imagePullPolicy: "Always"
  imagePullSecrets: []

  registry: "docker.software-univention.de"
  repository: "guardian-management-ui-management-ui"
  tag: "1.0.0"
  # -- Define image sha256 as an alternative to `tag`
  sha256: null

## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1

# -- Deployment resources for the listener container
resources: {}
  # requests:
  #   memory: "512Mi"
  #   cpu: "250m"
  # limits:
  #   memory: "4Gi"
  #   cpu: "4"

service:
  enabled: true
  type: "ClusterIP"
  ports:
    http:
      containerPort: 80
      port: 80
      protocol: "TCP"

  sessionAffinity:
    enabled: false
    timeoutSeconds: 10800

# -- Deployment resources for the dependency waiters
resourcesWaitForDependency: {}


autoscaling:
  enabled: false


persistence:
  data:
    storageClass: ""
    size: "1Gi"

...
