---

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []

guardianAuthorizationApi:
  home: "/guardian_service_dir"
  # -- Comma-separated list of hosts that are allowed to make cross-origin resource sharing (CORS) requests to the server.
  guardianAuthzCorsAllowedOrigins: "*"
  guardianAuthzAdapterSettingsPort: "env"
  guardianAuthzAdapterAppPersistencePort: "udm_data"
  guardianAuthzAdapterPolicyPort: "opa"
  guardianAuthzAdapterAuthenticationPort: "fast_api_oauth"
  isUniventionAppCenter: 0
  # -- The URL of the UDM REST API for data queries.
  udmDataAdapterUrl: "http://udm-rest-api/univention/udm"
  # -- Username for authenticating against the UDM REST API
  udmDataAdapterUsername: "admin"
  udmDataAdapterUsernameFile: "/var/secrets/udmDataAdapterUsername"
  # -- Password for authenticating against the UDM REST API
  udmDataAdapterPassword: null
  udmDataAdapterPasswordFile: "/var/secrets/udmDataAdapterPassword"
  opaAdapterUrl: "http://open-policy-agent:8181/"
  # -- OIDC well-known url
  oauthAdapterWellKnownUrl: "http://keycloak/realms/souvap/.well-known/openid-configuration"
  # -- Sets the log level of the application.
  guardianAuthzLoggingLevel: "DEBUG"
  # -- If set to True, the logging output is structured as a JSON object.
  guardianAuthzLoggingStructured: True
  # -- Defines the format of the log output, if not structured. The possible options are described in https://loguru.readthedocs.io/en/stable/api/logger.html.
  guardianAuthzLoggingFormat: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS ZZ}</green> | <level>{level}</level> | <level>{message}</level> | {extra}"


ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: true
  ingressClassName: "nginx"
  host: null
  paths:
    - pathType: Prefix
      path: /guardian/authorization
      backend:
        service:
          name: guardian-authorization-api
          port:
            number: 80
  tls:
    enabled: true
    secretName: ""

istio:
  # -- Set this to `true` in order to enable the installation on Istio related objects.
  enabled: false
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  virtualService:
    enabled: true
    annotations: {}
    # -- The paths configuration.
    # The default only grabs what is known to be handled by the UMC server.
    paths:
      - match: "prefix"
        path: "/guardian/authorization"
        rewrite: "/guardian/authorization/"
  gateway:
    enabled: false
    annotations:
    selectorIstio: "ingressgateway"
    externalGatewayName: "swp-istio-gateway"
    tls:
      enabled: true
      httpsRedirect: true
      secretName: ""


image:
  imagePullPolicy: "Always"
  imagePullSecrets: []

  registry: "docker.software-univention.de"
  repository: "guardian-authorization-api-authorization-api"
  tag: "2.0.0"
  # -- Define image sha256 as an alternative to `tag`
  sha256: null

## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1

# -- Deployment resources for the listener container
resources: {}
  # requests:
  #   memory: "512Mi"
  #   cpu: "250m"
  # limits:
  #   memory: "4Gi"
  #   cpu: "4"

service:
  enabled: true
  type: "ClusterIP"
  ports:
    http:
      containerPort: 8000
      port: 80
      protocol: "TCP"

  sessionAffinity:
    enabled: false
    timeoutSeconds: 10800

# -- Deployment resources for the dependency waiters
resourcesWaitForDependency: {}


autoscaling:
  enabled: false


persistence:
  data:
    storageClass: ""
    size: "1Gi"

...
