#!/bin/bash
#
# Univention guardian-server
#  Compile policies and run policy tests.
#
# SPDX-FileCopyrightText: 2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

docker run --rm -i \
  -v /usr/share/univention-guardian-server/policies:/policies:ro \
  ghcr.io/cerbos/cerbos:0.53.0@sha256:c3fe64202e3793b7e9c41c5cbfcf390a51fb28ebce0a7d70754155e70db839c4 compile --verbose \
  --tests=/policies/tests \
  /policies

exit $?
