---
{{ include "common.configMap" (dict "top" . "overrides" "guardian-authorization-api.configMap") }}

{{- define "guardian-authorization-api.configMap" }}

data:
{{- with .top.Values.guardianAuthorizationApi }}
  HOME: "{{ .home }}"
  GUARDIAN__AUTHZ__CORS__ALLOWED_ORIGINS: "{{ .guardianAuthzCorsAllowedOrigins }}"
  GUARDIAN__AUTHZ__ADAPTER__SETTINGS_PORT: "{{ .guardianAuthzAdapterSettingsPort }}"
  GUARDIAN__AUTHZ__ADAPTER__PERSISTENCE_PORT: "{{ .guardianAuthzAdapterAppPersistencePort }}"
  GUARDIAN__AUTHZ__ADAPTER__POLICY_PORT: "{{ .guardianAuthzAdapterPolicyPort }}"
  GUARDIAN__AUTHZ__ADAPTER__AUTHENTICATION_PORT: "{{ .guardianAuthzAdapteriAuthenticationPort }}"
  IS_UNIVENTION_APPCENTER: "{{ .isUniventionAppCenter }}"
  UDM_DATA_ADAPTER__URL: "{{ .udmDataAdapterUrl }}"
  UDM_DATA_ADAPTER__USERNAME: "{{ .udmDataAdapterUsername }}"
  UDM_DATA_ADAPTER__PASSWORD: "{{ .udmDataAdapterPassword }}"
  OPA_ADAPTER__URL: "{{ .opaAdapterUrl }}"
  GUARDIAN__AUTHZ__LOGGING__LEVEL: "{{ .guardianAuthzLoggingLevel }}"
  GUARDIAN__AUTHZ__LOGGING__STRUCTURED: "{{ .guardianAuthzLoggingStructured }}"
  GUARDIAN__AUTHZ__LOGGING__FORMAT: "{{ .guardianAuthzLoggingFormat }}"
  OAUTH_ADAPTER__WELL_KNOWN_URL: "{{ .oauthAdapterWellKnownUrl }}"
{{ end }}

{{ end }}
...
