"""Initial Schema

Revision ID: 1.0.0
Revises:
Create Date: 2023-09-14 12:59:51.704076

"""
import base64
import json
import os.path
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import insert, orm

# revision identifiers, used by Alembic.
revision: str = "1.0.0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_guardian_app(session, app_table, ns_table, role_table) -> int:
    app_data = {"name": "guardian", "display_name": "The Guardian Application"}
    app_id = session.execute(insert(app_table).values(app_data)).lastrowid
    ns_default = {
        "app_id": app_id,
        "name": "default",
        "display_name": "Default Namespace of the Guardian Application",
    }
    ns_protected = {
        "app_id": app_id,
        "name": "builtin",
        "display_name": "Builtin Namespace of the Guardian Application",
    }
    session.execute(insert(ns_table).values(ns_default))
    ns_id = session.execute(insert(ns_table).values(ns_protected)).lastrowid
    role_data = {
        "namespace_id": ns_id,
        "name": "app-admin",
        "display_name": "The app admin for the Guardian Application",
    }
    session.execute(insert(role_table).values(role_data))
    return ns_id


def create_builtin_conditions(session, cond_table, ns_id, cond_param_table):
    condition_path = (
        Path(os.path.dirname(os.path.realpath(__file__)))
        / "../1.0.0_builtin_conditions"
    )
    for data_file in condition_path.glob("*.json"):
        cond_name = data_file.stem
        with open(data_file, "r") as f:
            data = json.load(f)
        with open(condition_path / f"{cond_name}.rego", "rb") as f:
            code = f.read()
        cond = {
            **data,
            "code": base64.b64encode(code),
            "name": cond_name,
            "namespace_id": ns_id,
        }
        del cond["parameters"]
        cond_id = session.execute(insert(cond_table).values(cond)).lastrowid
        for cond_param in data["parameters"]:
            session.execute(
                insert(cond_param_table).values({**cond_param, "condition_id": cond_id})
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    app_table = op.create_table(
        "app",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    ns_table = op.create_table(
        "namespace",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["app.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id", "name"),
    )
    cond_table = op.create_table(
        "condition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("namespace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("documentation", sa.Text(), nullable=True),
        sa.Column("code", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["namespace_id"],
            ["namespace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "name"),
    )
    op.create_table(
        "context",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("namespace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["namespace_id"],
            ["namespace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "name"),
    )
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("namespace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["namespace_id"],
            ["namespace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "name"),
    )
    role_table = op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("namespace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["namespace_id"],
            ["namespace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "name"),
    )
    op.create_table(
        "capability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("namespace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column(
            "relation",
            sa.Enum("AND", "OR", name="capabilityconditionrelation"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["namespace_id"],
            ["namespace.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "name"),
    )
    cond_param_table = op.create_table(
        "condition_parameter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condition_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum(
                "ANY",
                "STRING",
                "FLOAT",
                "INT",
                "BOOLEAN",
                "ROLE",
                "CONTEXT",
                name="conditiontype",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["condition_id"],
            ["condition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "capability_condition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("capability_id", sa.Integer(), nullable=False),
        sa.Column("condition_id", sa.Integer(), nullable=False),
        sa.Column("kwargs", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["capability_id"], ["capability.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["condition_id"], ["condition.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "capability_permission",
        sa.Column("capability_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["capability_id"], ["capability.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permission.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("capability_id", "permission_id"),
    )
    # ### end Alembic commands ###

    # Setup Guardian default objects
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    ns_id = create_guardian_app(session, app_table, ns_table, role_table)
    create_builtin_conditions(session, cond_table, ns_id, cond_param_table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("capability_permission")
    op.drop_table("capability_condition")
    op.drop_table("condition_parameter")
    op.drop_table("capability")
    op.drop_table("role")
    op.drop_table("permission")
    op.drop_table("context")
    op.drop_table("condition")
    op.drop_table("namespace")
    op.drop_table("app")
    # ### end Alembic commands ###
