#!/usr/share/ucs-test/runner bash
# SPDX-FileCopyrightText: 2023 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only
#
## desc: run unit tests in container
## tags: [guardian, guardian-management-api]
## exposure: dangerous
## packages: []
## bugs: []
## external-junit: /tmp/guardian-in_container_management_api.xml


APP="guardian-management-api"
/usr/share/guardian/scripts/guardian_scripts/set_up_tests.sh

declare -a CMD=(sh -c "
cd /app/management-api/tests &&
python3 -m pytest --junit-xml=/tmp/junit.xml --junit-prefix=99_guardian.10_in_container_management_api")


echo "Running in container: ${CMD[@]}"

univention-app shell "$APP" "${CMD[@]}" || (rv=$?; pkill -f '^/usr/bin/python.*pytest$'; exit $rv)
rm -f /tmp/guardian-in_container_management_api.xml
univention-app shell "$APP" cat /tmp/junit.xml > /tmp/guardian-in_container_management_api.xml
