---
{{ include "common.configMap" (dict "top" . "overrides" "guardian-management.configMap") }}

{{- define "guardian-management.configMap" }}

data:
{{- with .top.Values.guardianManagementApi }}
  HOME: "{{ .home }}"
  GUARDIAN__MANAGEMENT__CORS__ALLOWED_ORIGINS: "{{ .guardianManagementCorsAllowedOrigins }}"
  GUARDIAN__MANAGEMENT__ADAPTER__SETTINGS_PORT: "{{ .guardianManagementAdapterSettingsPort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__APP_PERSISTENCE_PORT: "{{ .guardianManagementAdapterAppPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__CONDITION_PERSISTENCE_PORT: "{{ .guardianManagementAdapterConditionPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__CONTEXT_PERSISTENCE_PORT: "{{ .guardianManagementAdapterContextPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__NAMESPACE_PERSISTENCE_PORT: "{{ .guardianManagementAdapterNamespacePersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__PERMISSION_PERSISTENCE_PORT: "{{ .guardianManagementAdapterPermissionPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__ROLE_PERSISTENCE_PORT: "{{ .guardianManagementAdapterRolePersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__CAPABILITY_PERSISTENCE_PORT: "{{ .guardianManagementAdapterCapabilityPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__AUTHENTICATION_PORT: "{{ .guardianManagementAdapterAuthenticationPort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__AUTHORIZATION_API_URL: "{{ .guardianManagementAdapterAuthorizationApiUrl }}"
  GUARDIAN__MANAGEMENT__ADAPTER__RESOURCE_AUTHORIZATION_PORT: "{{ .guardianManagementAdapterResourceAuthorizationPort }}"
  # NOTE: Seems to be only used during stopping the containers for univention-app command
  # We can probably drop it, since it is used on some bash termiation script
  IS_UNIVENTION_APPCENTER: "{{ .isUniventionAppCenter }}"
  SQL_PERSISTENCE_ADAPTER__DIALECT: "{{ .sqlPersistenceAdapterDialect }}"
  SQL_PERSISTENCE_ADAPTER__DB_NAME: "{{ .sqlPersistenceAdapterDbName }}"
  OAUTH_ADAPTER__WELL_KNOWN_URL: "{{ .oauthAdapterWellKnownUrl }}"
  # FIXME: This is a secret
  OAUTH_ADAPTER__M2M_SECRET: "{{ .oauthAdapterM2mSecret }}"
  GUARDIAN__MANAGEMENT__LOGGING__LEVEL: "{{ .guardianManagementLoggingLevel }}"
  GUARDIAN__MANAGEMENT__LOGGING__STRUCTURED: "{{ .guardianManagementLoggingStructured }}"
  GUARDIAN__MANAGEMENT__LOGGING__FORMAT: "{{ .guardianManagementLoggingFormat }}"
  GUARDIAN__MANAGEMENT__BASE_URL: "{{ .guardianManagementBaseUrl }}"
{{ end }}

{{- with .top.Values.guardianManagementUi }}
  VITE__MANAGEMENT_UI__ADAPTER__AUTHENTICATION_PORT: "{{ .viteManagementUiAdapterAuthenticationPort }}"
  VITE__MANAGEMENT_UI__ADAPTER__DATA_PORT: "{{ .viteManagementUiAdapterDataPort }}"
  VITE__API_DATA_ADAPTER__URI: "{{ .viteApiDataAdapterUri }}"
  VITE__KEYCLOAK_AUTHENTICATION_ADAPTER__SSO_URI: "{{ .viteKeycloakAuthenticationAdapterSsoUri }}"
  VITE__KEYCLOAK_AUTHENTICATION_ADAPTER__REALM: "{{ .viteKeycloakAuthenticationAdapterRealm }}"
  VITE__KEYCLOAK_AUTHENTICATION_ADAPTER__CLIENT_ID: "{{ .viteKeycloakAuthenticationAdapterClientId }}"
{{ end }}

{{ end }}
...
