apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"

  resource: "document"

  rules:
    - actions:
        - view
      effect: EFFECT_ALLOW
      roles:
        - user
        - admin

    - actions:
        - create
        - update
        - delete
      effect: EFFECT_ALLOW
      roles:
        - admin
