#!/bin/sh

if test "$1" -eq 256 ; then
  e=$((128 + $2))
else
  e="$1"
fi

if [ -z ${IS_UNIVENTION_APPCENTER+x} ]; then
  echo "$e" > /run/s6-linux-init-container-results/exitcode
  /run/s6/basedir/bin/halt
fi
