#!/bin/bash

###############################################################################
#                                                                             #
#  Dynamically generates the preinst file from templates.                     #
#                                                                             #
###############################################################################

APP_NAME="guardian-management-ui"
PREINST_TEMPLATE="templates/preinst.tmpl"
APPCENTER_COMMON_DIR="../appcenter-common"
CONFIGURE_KEYCLOAK_TEMPLATE="templates/configure-keycloak.tmpl"
KEYCLOAK_TEMP_FILE="configure-keycloak.temp"

cp $PREINST_TEMPLATE preinst
cp $CONFIGURE_KEYCLOAK_TEMPLATE $KEYCLOAK_TEMP_FILE

# Assemble the configure-keycloak script
./$APPCENTER_COMMON_DIR/keycloak/generate-configure-keycloak.sh \
    $APP_NAME \
    $CONFIGURE_KEYCLOAK_TEMPLATE \
    $KEYCLOAK_TEMP_FILE
sed -i -e "/%GUARDIAN-KEYCLOAK%/r $KEYCLOAK_TEMP_FILE" -e "/%GUARDIAN-KEYCLOAK%/d" preinst
