---
{{ include "common.configMap" (dict "top" . "overrides" "guardian-management-api.configMap") }}

{{- define "guardian-management-api.configMap" }}

data:
{{- with .top.Values.guardianManagementApi }}
  HOME: "{{ .home }}"
  GUARDIAN__MANAGEMENT__CORS__ALLOWED_ORIGINS: "{{ .guardianManagementCorsAllowedOrigins }}"
  GUARDIAN__MANAGEMENT__ADAPTER__SETTINGS_PORT: "{{ .guardianManagementAdapterSettingsPort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__APP_PERSISTENCE_PORT: "{{ .guardianManagementAdapterAppPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__CONDITION_PERSISTENCE_PORT: "{{ .guardianManagementAdapterConditionPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__CONTEXT_PERSISTENCE_PORT: "{{ .guardianManagementAdapterContextPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__NAMESPACE_PERSISTENCE_PORT: "{{ .guardianManagementAdapterNamespacePersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__PERMISSION_PERSISTENCE_PORT: "{{ .guardianManagementAdapterPermissionPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__ROLE_PERSISTENCE_PORT: "{{ .guardianManagementAdapterRolePersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__CAPABILITY_PERSISTENCE_PORT: "{{ .guardianManagementAdapterCapabilityPersistencePort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__AUTHENTICATION_PORT: "{{ .guardianManagementAdapterAuthenticationPort }}"
  GUARDIAN__MANAGEMENT__ADAPTER__AUTHORIZATION_API_URL: "{{ .guardianManagementAdapterAuthorizationApiUrl }}"
  GUARDIAN__MANAGEMENT__ADAPTER__RESOURCE_AUTHORIZATION_PORT: "{{ .guardianManagementAdapterResourceAuthorizationPort }}"
  # NOTE: Seems to be only used during stopping the containers for univention-app command
  # We can probably drop it, since it is used on some bash termiation script
  IS_UNIVENTION_APPCENTER: "{{ .isUniventionAppCenter }}"
  OAUTH_ADAPTER__WELL_KNOWN_URL: "{{ .oauthAdapterWellKnownUrl }}"
  # FIXME: This is a secret
  OAUTH_ADAPTER__M2M_SECRET: "{{ .oauthAdapterM2mSecret }}"
  OAUTH_ADAPTER__M2M_SECRET_FILE: "{{ .oauthAdapterM2mSecretFile }}"
  GUARDIAN__MANAGEMENT__LOGGING__LEVEL: "{{ .guardianManagementLoggingLevel }}"
  GUARDIAN__MANAGEMENT__LOGGING__STRUCTURED: "{{ .guardianManagementLoggingStructured }}"
  GUARDIAN__MANAGEMENT__LOGGING__FORMAT: "{{ .guardianManagementLoggingFormat }}"
  GUARDIAN__MANAGEMENT__BASE_URL: "{{ .guardianManagementBaseUrl }}"
  SQL_PERSISTENCE_ADAPTER__DIALECT: "{{ .sqlPersistenceAdapterDialect }}"
{{ end }}

  {{- if .top.Values.postgresql.bundled }}
  SQL_PERSISTENCE_ADAPTER__HOST: "{{ include "common.names.dependency.fullname" (dict "chartName" "postgresql" "chartValues" .top.Values.postgresql "context" $.top) }}"
  SQL_PERSISTENCE_ADAPTER__PORT: "{{ .top.Values.postgresql.primary.service.ports.postgresql }}"
  {{- else }}
  SQL_PERSISTENCE_ADAPTER__HOST: "{{ .top.Values.postgresql.connection.host }}"
  SQL_PERSISTENCE_ADAPTER__PORT: "{{ .top.Values.postgresql.connection.port }}"
  {{- end }}
  SQL_PERSISTENCE_ADAPTER__USERNAME: "{{ .top.Values.postgresql.auth.username }}"
  SQL_PERSISTENCE_ADAPTER__DB_NAME: "{{ .top.Values.postgresql.auth.database }}"
  SQL_PERSISTENCE_ADAPTER__PASSWORD: "{{ .top.Values.postgresql.auth.password }}"

{{ end }}
...
